name: GITCLAW-WORKFLOW-AGENT

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    if: >
      (
        github.event_name == 'issues' &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.issue.author_association)
      ) ||
      (
        github.event_name == 'issue_comment' &&
        github.event.comment.user.login != 'github-actions[bot]' &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Guard
        run: bun .GITCLAW/lifecycle/GITCLAW-ENABLED.ts

      - name: Preinstall
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun .GITCLAW/lifecycle/GITCLAW-INDICATOR.ts

      - name: Install dependencies
        run: cd .GITCLAW && bun install --frozen-lockfile

      - name: Run
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun .GITCLAW/lifecycle/GITCLAW-AGENT.ts
